version: '2'
services:
    reqman-app:
        image: reqman
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://reqman-mariadb:3306/reqman
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=reqman-elasticsearch:9300
        ports:
            - 8080:8080
    reqman-mariadb:
        extends:
            file: mariadb.yml
            service: reqman-mariadb
    reqman-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: reqman-elasticsearch
